name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-22.04-arm, macos-13, macos-14, windows-2019]

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.21.0

      - uses: actions/upload-artifact@v4
        with:
          name: knot_floer_homology_${{ matrix.os }}_wheels
          path: ./wheelhouse/*.whl
