name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        python-version: [3.7]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python ${{ matrix.python-version }}
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel cython

      - name: Build and test
        run: |
          python setup.py bdist_wheel
          pip install --no-index --find-links=./dist knot_floer_homology
          python -m knot_floer_homology.test

      - uses: actions/upload-artifact@v2
        with:
          path: ./dist/*.whl
