name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Build wheels
        uses: pypa/cibuildwheel
        run: |
          python -m cibuildwheel --output-dir wheelhouse
        env:
          # Skip Python 2.7 and 3.5, 32 bit Linux, and PyPy
          CIBW_SKIP: cp27-* cp35-* *-manylinux_i686 *musllinux* pp*
          CIBW_ARCHS_MACOS: "x86_64 arm64 universal2"
          CIBW_BEFORE_BUILD: pip install cython
          CIBW_REPAIR_WHEEL_COMMAND_LINUX: auditwheel repair --strip -w {dest_dir} {wheel}
          CIBW_TEST_COMMAND: python -m knot_floer_homology.test

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
