name: Build universal2

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build universal2 wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13]

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.21.0
        env:
          CIBW_ARCHS: universal2
          
      - uses: actions/upload-artifact@v4
        with:
          name: knot_floer_homology_universal2_${{ matrix.os }}_wheels
          path: ./wheelhouse/*.whl
